version: "3.4"
services:
  nginx:
    build: './docker/nginx/'
    container_name: container-nginx
    depends_on:
      - php
      - mysql
    networks:
      - backend
    ports:
      - '${NGINX_PORT_HTTP}:80'
      - '${NGINX_PORT_HTTPS}:443'
    volumes:
      - ./root/:/var/www/html/
  php:
    build:
      context: './docker/php/'
    container_name: container-php
    networks:
      - backend
    volumes:
      - ./root/:/var/www/html/
      - ./docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
  mysql:
    image: mysql:8.0
    command: [
      'mysqld',
      '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_bin',
      --default-authentication-plugin=mysql_native_password,
    ]
    ports:
      - '${DB_CONTAINER_PORT}:3306'
    container_name: container-mysql
    networks:
      - backend
    volumes:
      - container_mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: container-phpmyadmin
    environment:
      - PMA_ARBITRARY=10
      - PMA_HOST=mysql
      - PMA_PORT=3306

    restart: always
    ports:
      - '${PHPMYADMIN_PORT}:80'
    networks:
      - backend

networks:
  backend:

volumes:
  container_mysql_data: {}
