<?php

return [
    'ERROR_STATUS' => [
        'FAIL' => 0,
        'SUCCESS' => 1,
        'FAIL_AND_RELOAD' => '2',
    ],
    'USER_NAME_HIDDEN_TRUE' => 0,
    'USER_NAME_HIDDEN_FALSE' => 1,
    'TOP_STATISTIC_DEFAULT_LIMIT' => 5,
    'DEFAULT_PASSWORD_LENGTH' => 8,
    'DEFAULT_PAGINATION' => 10,
    'DEFAULT_PAGINATION_USER' => 12,
    'DEFAULT_NEW_BOOK' => 7,
    'DEFAULT_TO_DATE' => 10,
    'DEFAULT_MIN_NUMBER' => 0,
    'DEFAULT_MAX_NUMBER' => 100,
    'USER_BORROW_COUNT' => 3,
    'QUANTITY_BOOKS_LEFT_IN_STOCK' =>0,
    'DEFAULT_CATEGORIES_IN_BOOK_DETAILS' => 3,
    'QUANTITY_BORROW_BOOK' => 1,
    'STATUS_BORROWER_2' => 2,
    'QUANTITY_RENEWAL_BOOK' => 1,
    'STATUS_BORROWER_1' => 1,
    'STATUS_BORROWER_0' => 0,
    'ALLOWED_RENEWAL_0' => 0,
    'EMAIL_REGEX' => 'regex:/[\w.-]+@([\w-]+\.)+[\w-]{2,4}$/i',
];